version: '2'

services:

    phenology-db:

        image: bertt/phenology-db

        ports:

            - "5432:5432"

        environment:
            - POSTGRES_DB=locophoto 
            - POSTGRES_USER=geodb
            - POSTGRES_PASSWORD=geodb
            
    phenology-service:

        image: bertt/phenology-service

        ports:

            - "3100:3100"
