version: '2'

services:

    phenology-db:

        image: bertt/phenology-db

        ports:

            - "5432:5432"
            
        environment:
            - ENV POSTGRES_USER=geodb
            
            - ENV POSTGRES_PASSWORD=geodb
            
            - ENV POSTGRES_DB=locophoto
            
    phenology-service:

        image: bertt/phenology-service

        ports:

            - "3100:3100"
